import {spawn} from 'node:child_process';
import {writeFile,mkdir,readFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
// Fixed synthetic ports. Start backend on 8571 and scripts/local_investment_ui.mjs on 5197.
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../frontend/node_modules/.cache/investment-execution-final');
await mkdir(root,{recursive:true});
const profile=path.join(root,'profile-'+Date.now());await mkdir(profile,{recursive:true});
const chrome=spawn('C:/Program Files/Google/Chrome/Application/chrome.exe',['--headless=new','--disable-gpu','--no-first-run','--no-default-browser-check','--remote-debugging-port=0','--remote-debugging-address=127.0.0.1','--user-data-dir='+profile,'--host-resolver-rules=MAP * ~NOTFOUND, EXCLUDE 127.0.0.1, EXCLUDE localhost','about:blank'],{windowsHide:true,stdio:'ignore'});
const delay=ms=>new Promise(r=>setTimeout(r,ms));let ws,oldBackend=false,loseTradeResponse=false,delayPortfolio='',heldBundle=null;
const qaDay=new Date(Date.now()+9*3600000).toISOString().slice(0,10);
const summary=[],requests=[],requestPaths=new Map();
try{
 let targets;
 for(let i=0;i<30;i++){try{const port=(await readFile(path.join(profile,'DevToolsActivePort'),'utf8')).split('\n')[0];targets=await(await fetch('http://127.0.0.1:'+port+'/json/list')).json();break;}catch{await delay(200);}}
 if(!targets)throw new Error('Chrome CDP unavailable');
 ws=new WebSocket(targets.find(t=>t.type==='page').webSocketDebuggerUrl);
 await new Promise((res,rej)=>{ws.addEventListener('open',res,{once:true});ws.addEventListener('error',rej,{once:true});});
 let id=0;const pending=new Map();
 const rpc=(method,params={})=>new Promise((res,rej)=>{const n=++id;const timer=setTimeout(()=>{pending.delete(n);rej(new Error('CDP timeout: '+method));},15000);pending.set(n,{res,rej,timer});ws.send(JSON.stringify({id:n,method,params}));});
 ws.addEventListener('message',async event=>{
  const d=JSON.parse(event.data);
  if(d.id){const p=pending.get(d.id);pending.delete(d.id);if(!p)return;clearTimeout(p.timer);if(d.error)p.rej(new Error(d.error.message));else p.res(d.result);}
  if(d.method==='Page.javascriptDialogOpening')await rpc('Page.handleJavaScriptDialog',{accept:true});
  if(d.method==='Network.requestWillBeSent')requestPaths.set(d.params.requestId,new URL(d.params.request.url).pathname);
  if(d.method==='Log.entryAdded' && true)console.log('BROWSER_DIAGNOSTIC',d.params.entry.text);
  if(d.method==='Network.loadingFailed')console.log('NETWORK_FAILURE',JSON.stringify({path:requestPaths.get(d.params.requestId),error:d.params.errorText,cors:d.params.corsErrorStatus,blocked:d.params.blockedReason}));
  if(d.method==='Network.requestWillBeSent' && d.params.request.url.startsWith('http://127.0.0.1:5197/'))requests.push({method:d.params.request.method,path:new URL(d.params.request.url).pathname});
  if(d.method==='Fetch.requestPaused'){if(d.params.request.url.includes('/api/dashboard/bundle')){if(delayPortfolio && d.params.request.method==='GET' && new URL(d.params.request.url).searchParams.get('portfolio_id')===delayPortfolio){heldBundle=d.params.requestId;return;}await rpc('Fetch.continueRequest',{requestId:d.params.requestId});return;}if(d.params.request.url.endsWith('/api/trades/batch')){if(loseTradeResponse && d.params.request.method==='POST' && d.params.responseStatusCode===200){loseTradeResponse=false;await rpc('Fetch.failRequest',{requestId:d.params.requestId,errorReason:'ConnectionReset'});}else await rpc('Fetch.continueRequest',{requestId:d.params.requestId});return;}if(oldBackend)await rpc('Fetch.fulfillRequest',{requestId:d.params.requestId,responseCode:404,responseHeaders:[{name:'Content-Type',value:'application/json'},{name:'Access-Control-Allow-Origin',value:'http://127.0.0.1:5197'}],body:Buffer.from('{"detail":"Synthetic old backend"}').toString('base64')});else await rpc('Fetch.continueRequest',{requestId:d.params.requestId});}
 });
 const evaljs=async expression=>{const r=await rpc('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw new Error(r.exceptionDetails.exception?.description || r.exceptionDetails.text);return r.result.value;};
 const check=(v,m)=>{if(!v)throw new Error(m);};
 const wait=async(expression,desc)=>{for(let i=0;i<60;i++){if(await evaljs(expression))return;await delay(150);}throw new Error('Timeout: '+desc+'; '+await evaljs("document.body.innerText.slice(-3500)"));};
 const visible="e.getClientRects().length && !e.closest('[hidden]')";
 const click=async text=>{await wait("[...document.querySelectorAll('button')].some(e=>"+visible+" && e.textContent.trim()==="+JSON.stringify(text)+" && !e.disabled)",'enabled '+text);const ok=await evaljs("(()=>{const e=[...document.querySelectorAll('button')].find(e=>"+visible+" && e.textContent.trim()==="+JSON.stringify(text)+");if(!e || e.disabled)return false;e.click();return true;})()");check(ok,'Button unavailable: '+text);await delay(170);};
 const value=async(selector,v)=>{await evaljs("(()=>{const e=[...document.querySelectorAll("+JSON.stringify(selector)+")].find(e=>"+visible+");if(!e)throw new Error('Input missing: '+ "+JSON.stringify(selector)+");const proto=e instanceof HTMLSelectElement?HTMLSelectElement.prototype:e instanceof HTMLTextAreaElement?HTMLTextAreaElement.prototype:HTMLInputElement.prototype;Object.getOwnPropertyDescriptor(proto,'value').set.call(e,"+JSON.stringify(String(v))+");e.dispatchEvent(new Event('input',{bubbles:true}));e.dispatchEvent(new Event('change',{bubbles:true}));})()");await delay(100);};
 const tick=async label=>{const ok=await evaljs("(()=>{const e=[...document.querySelectorAll('label')].find(e=>"+visible+" && e.textContent.includes("+JSON.stringify(label)+"));const input=e?.querySelector('input[type=checkbox]');if(!input || input.disabled)return false;if(!input.checked)input.click();return true;})()");check(ok,'Confirmation unavailable: '+label);await delay(100);};
 const tab=async t=>{await wait("Boolean(window.qaVisible('[aria-label=\"포트폴리오 화면 선택\"]') && !window.qaVisible('[aria-label=\"포트폴리오 화면 선택\"]').disabled) || [...document.querySelectorAll('.desktop-tabs .tab-btn')].some(e=>e.getClientRects().length && !e.disabled)",'tab navigation ready');if(await evaljs("Boolean(window.qaVisible('[aria-label=\"포트폴리오 화면 선택\"]')?.getClientRects().length)"))await value('[aria-label="포트폴리오 화면 선택"]',t);else{const index=['tab1','accounts','tab2','tab3','tab4','tab5','tab6','tab8'].indexOf(t);const ok=await evaljs("(()=>{const b=document.querySelectorAll('.desktop-tabs .tab-btn')["+index+"];if(!b || b.disabled)return false;b.click();return true;})()");check(ok,'Desktop tab unavailable');}await delay(250);};
 const noBuffers=async()=>{if(await evaljs("Boolean(document.querySelector('[aria-label=\"가격 여유율\"]'))")){await evaljs("[...document.querySelectorAll('details')].find(e=>e.querySelector('summary')?.textContent.includes('여유자금 설정')).open=true");await value('[aria-label=\"가격 여유율\"]',0);await value('[aria-label=\"환율 여유율\"]',0);}};
 const current=()=>evaljs("window.qaVisible('.execution-current h3')?.textContent");
 const stat=()=>evaljs("(async()=>{const session=JSON.parse(sessionStorage.getItem('portfolio_api_session_v1'));const r=await fetch('http://127.0.0.1:5197/qa/investment-ledger',{headers:{Authorization:'Bearer '+session.access_token}});if(!r.ok)throw new Error('Synthetic status failed');return r.json();})()");
 const screenshot=async name=>{if(['input-390','existing-390'].includes(name)){await evaljs("window.qaVisible('.execution-input')?.scrollIntoView({block:'start'})");await delay(100);}const r=await rpc('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});await writeFile(path.join(root,name+'.png'),Buffer.from(r.data,'base64'));};
 await rpc('Page.addScriptToEvaluateOnNewDocument',{source:"window.qaVisible=selector=>[...document.querySelectorAll(selector)].find(e=>e.getClientRects().length && !e.closest('[hidden]'));"});
 await rpc('Page.enable');await rpc('Runtime.enable');await rpc('Network.enable');await rpc('Log.enable');
 await rpc('Fetch.enable',{patterns:[{urlPattern:'*://127.0.0.1:5197/api/investments/capabilities',requestStage:'Request'},{urlPattern:'*://127.0.0.1:5197/api/trades/batch',requestStage:'Response'},{urlPattern:'*://127.0.0.1:5197/api/dashboard/bundle*',requestStage:'Request'}]});
 await rpc('Emulation.setDeviceMetricsOverride',{width:390,height:1000,deviceScaleFactor:1,mobile:true});
 await rpc('Page.navigate',{url:'http://127.0.0.1:5197/'});
 await wait("Boolean(window.qaVisible('input[type=password]'))",'login');
 await value('input[type=password]','ui-test-only');await click('접속하기');
 await wait("Boolean(window.qaVisible('[aria-label=\"포트폴리오 화면 선택\"]'))",'dashboard');
 await delay(350);
 check(!requests.some(r=>r.path.startsWith('/api/investments')),'Dashboard made an investment request');
 summary.push('Initial dashboard has no new execution request');
 await tab('tab3');
 check(!await evaljs("Boolean(window.qaVisible('.plan-save'))"),'Save form shown before calculation');
 const managementBefore=await stat();
 await value('.section-card input[type=number]:not([disabled])','1000000');
 await click('🚀 리밸런싱 전략 계산하기');
 await wait("Boolean(window.qaVisible('.plan-save'))",'calculated plan save form');
 check(await evaljs("(()=>{const save=window.qaVisible('.plan-save');const results=save.previousElementSibling;return results.innerText.includes('리밸런싱 실행 지시서') && save.nextElementSibling.matches('.saved-plans');})()"),'Strategy/results/save/history order incorrect');
 await value('[aria-label="계획 이름"]','브라우저 검증용 미사용 계획');
 await click('현재 계산 결과를 계획으로 저장');
 await wait("Boolean(window.qaVisible('.plan-save-complete'))",'named plan saved');
 await evaljs("window.qaVisible('.plan-save').scrollIntoView({block:'start'})");await screenshot('plan-save-390');
 await click('이 계획으로 투자 실행 준비');
 await wait("Boolean(window.qaVisible('[aria-label=\"투자 실행 계획\"]'))",'immediate saved-plan handoff');
 check(await evaljs("window.qaVisible('[aria-label=\"투자 실행 계획\"]').innerText.includes('브라우저 검증용 미사용 계획')"),'Saved plan handoff selected wrong plan');
 await tab('tab3');await click('저장한 계획 조회');
 await wait("document.body.innerText.includes('브라우저 검증용 미사용 계획')",'new saved plan listed');
 await evaljs("[...document.querySelectorAll('.saved-plans details')].find(e=>e.querySelector('summary').textContent.includes('브라우저 검증용 미사용 계획')).open=true");
 await click('계획 삭제');
 await wait("!document.body.innerText.includes('브라우저 검증용 미사용 계획')",'unused plan deleted');
 check(JSON.stringify(await stat())===JSON.stringify(managementBefore),'Save/preparation/delete changed journal or cycles');
 summary.push('Calculate/results/save order, named plan, immediate execution handoff and unused deletion preserve journal');
 await delay(700);if(await evaljs("document.body.innerText.includes('Failed to fetch')"))await click('저장한 계획 조회');
 await wait("document.body.innerText.includes('10월 적립 투자')",'saved plans');
 await evaljs("window.qaVisible('details.trade-row-card').open=true");
 await click('이 계획으로 투자 실행 준비');
 await wait("Boolean(window.qaVisible('[aria-label=\"투자 실행 계획\"]'))",'start form');
 const before=await stat();
 check(await evaljs("window.qaVisible('[aria-label=\"추가 투자 입금액\"]').value==='0'"),'Existing CMA cash counted as new income');
 await value('[aria-label="투자 대표 계좌"]','qa_cma');await value('[aria-label="추가 투자 입금액"]','1000000');await evaljs("[...document.querySelectorAll('details')].find(e=>e.querySelector('summary')?.textContent.includes('여유자금 설정')).open=true");await value('[aria-label="가격 여유율"]',0);await value('[aria-label="환율 여유율"]',0);await noBuffers();await click('필요한 작업 미리 확인');
 await wait("Boolean(window.qaVisible('.execution-start-review'))",'preview');
 check(JSON.stringify(await stat())===JSON.stringify(before),'Preparing workflow changed journal');
 await tick('자금 사용 범위와 목표');await click('확인한 계획으로 투자 시작');
 await wait("Boolean(window.qaVisible('.execution-current h3'))",'cycle');
 check((await stat()).cycles===1,'Cycle was not persisted');
 check((await stat()).trades===before.trades,'Start changed trades');
 await rpc('Page.reload');await wait("Boolean(window.qaVisible('[aria-label=\"포트폴리오 화면 선택\"]'))",'reload dashboard');await tab('tab8');await wait("Boolean(window.qaVisible('.execution-current'))",'resumed cycle');
 summary.push('Plan handoff, preview/start no journal change, reload resumes one cycle');
 await click('새 실행 내역 입력');await click('직접 입력');
 await delay(500);
 // The synthetic quote fixture can need one metadata refresh after parallel reads.
 if(await evaljs("document.body.innerText.includes('입출금 기록을 조회 중') && Boolean(window.qaVisible('.execution-journal-input [role=alert]'))"))await evaljs("window.qaVisible('header button[title=\"새로고침\"]')?.click()");
 await wait("Boolean(window.qaVisible('[aria-label=\"입출금 금액\"]'))",'manual investment funding form');
 const fundingBefore=await stat();
 await value('[aria-label="입출금 금액"]','1000000');
 await tick('외부 입출금이며');await click('외부 입출금 기록 저장');
 await wait("!window.qaVisible('#execution-input-panel')",'manual investment funding returns to progress');
 await wait("!window.qaVisible('[aria-label=\"포트폴리오 화면 선택\"]').disabled",'manual funding releases navigation lock');
 const funded=await stat();
 check(funded.cash.find(a=>a.id==='qa_cma').deposit_krw===fundingBefore.cash.find(a=>a.id==='qa_cma').deposit_krw+1000000,'Manual funding cash mismatch');
 check(funded.trades===fundingBefore.trades,'Manual funding created a trade');
 await tab('tab4');await tab('tab8');await wait("window.qaVisible('.execution-current h3')?.textContent.includes('자금 이동')",'funding advances to transfer');
 summary.push('Manual external deposit records once, advances to transfer, releases performance/navigation locks and returns to investment progress');

 const box=await evaljs("(()=>{const e=window.qaVisible('.execution-record');e.scrollIntoView({block:'center'});const b=e.getBoundingClientRect();return {x:b.x+b.width/2,y:b.y+b.height/2};})()");
 await rpc('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[box]});await rpc('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
 await wait("Boolean(window.qaVisible('#execution-input-panel'))",'touch input');
 await click('직접 입력');await value('[aria-label="이체 금액"]',180000);
 await tick('실제 이체한 계좌');
 await click('확인한 이체 장부에 반영');
 await wait("!window.qaVisible('#execution-input-panel')",'transfer recorded');
 check((await stat()).cash.find(a=>a.id==='qa_isa').deposit_krw===180000,'ISA transfer balance mismatch');
 await click('새 실행 내역 입력');await click('직접 입력');await value('[aria-label="이체 금액"]',560000);await tick('실제 이체한 계좌');await click('확인한 이체 장부에 반영');
 await wait("!window.qaVisible('#execution-input-panel')",'US funding recorded');
 check((await stat()).cash.find(a=>a.id==='qa_acc').deposit_krw===560000,'US transfer balance mismatch');
 await click('새 체결 내역 입력');
 const nh='[NH투자증권] 매수 주문체결 알림\n계좌번호 : 123-45-67***2\n종목명 : ACE 미국10년국채액티브\n종목코드 : 0085P0\n체결종류 : 매수 전량 체결\n체결수량 : 7주\n체결단가 : 9,000원(체결평균단가)\n주문번호 : 801';
 await value('[aria-label="NH 알림"]',nh);
 await tab('tab4');check(await evaljs("window.qaVisible('[aria-label=\"NH 알림\"]').value===''"),'Tab 5 adopted the task draft');
 check(!await evaljs("document.body.innerText.includes('현재 입력을 이 투자')"),'Tab 5 still requires investment consent');
 await value('[aria-label="NH 알림"]',nh);await click('알림을 확인 목록에 추가');
 await tick('계좌·날짜·순서·금액');await click('확인한 알림 1건 장부에 일괄 반영');
 await wait("!window.qaVisible('[aria-label=\"알림 1 계좌\"]')",'independent tab 5 trade saved');
 const independent=await stat();check(independent.holdings.find(h=>h.asset_id==='qa_nh_bond').quantity===7,'Tab 5 trade not in singleton journal');
 await tab('tab8');check(await evaljs("window.qaVisible('[aria-label=\"NH 알림\"]').value.includes('801')"),'Tab 8 draft was lost after independent tab 5 save');
 await click('투자 진행으로 돌아가기');
 check(await evaljs("window.qaVisible('.execution-quantities div:nth-child(2) strong').textContent.includes('0')"),'Tab 5 trade was silently attached');
 await click('기록한 거래 가져오기');
 await wait("Boolean(window.qaVisible('.execution-candidate input'))",'existing journal candidate');
 await screenshot('existing-390');
 await evaljs("window.qaVisible('.execution-candidate input').click()");await click('이번 투자 회차에 연결');
 await wait("Boolean(window.qaVisible('.execution-current'))",'existing record linked');
 check(JSON.stringify((await stat()).cash)===JSON.stringify(independent.cash),'Existing import changed cash');
 check((await stat()).trades===independent.trades,'Existing import duplicated trade');
 check(await evaljs("window.qaVisible('.execution-quantities div:last-child strong').textContent.includes('13')"),'Imported trade did not reduce remaining target');
 await screenshot('partial-390');
 summary.push('Tab 5 freely saves while tab 8 has a draft; draft remains separate; existing trade import adds progress without another journal/cash change');
 await click('새 체결 내역 입력');
 await screenshot('input-390');
 await value('[aria-label="NH 알림"]',nh.replace('7주','13주').replace('801','802'));await click('알림을 확인 목록에 추가');
 await tick('계좌·날짜·순서·금액');await click('체결 내역 저장 (1건)');await wait("!window.qaVisible('#execution-input-panel')",'new linked trade saved');
 check((await stat()).holdings.find(h=>h.asset_id==='qa_nh_bond').quantity===20,'Tab 8 new trade missing from common holdings');
 await tab('tab4');await click('기록 조회');
 await wait("document.body.innerText.includes('매수') && Boolean(window.qaVisible('.history-record-list'))",'tab 5 shared journal records');
 await evaljs("[...document.querySelectorAll('.history-record-detail')].forEach(e=>e.open=true)");
 await wait("document.body.innerText.includes('수량 13')",'tab 8 fill in tab 5 details');
 await screenshot('journal-390');await tab('tab8');
 summary.push('New tab 8 fill appears in tab 5 record history and updates the same holdings');
 await click('새 실행 내역 입력');
 const fx='[NH투자증권] 환전내역 안내\n환전일자 : 10월 10일\n계좌명 : 검*증\n환전구분 : 외화매수\n통화명 : USD\n우대율 : 100%\n환율 : 1,400\n외화금액 : USD 400.00\n원화금액 : 560,000'.replace('10월 10일',Number(qaDay.slice(5,7))+'월 '+Number(qaDay.slice(8))+'일');
 await value('[aria-label="NH 알림"]',fx);await click('알림을 확인 목록에 추가');await wait("document.body.innerText.includes('고시환율')",'FX parse');
 await tick('계좌·날짜·순서·금액');await click('실행 내역 저장 (1건)');await wait("!window.qaVisible('#execution-input-panel')",'FX saved');
 check((await stat()).cash.find(a=>a.id==='qa_acc').deposit_usd===500,'Existing USD not preserved');
 await click('새 체결 내역 입력');
 check(await evaljs("Number(window.qaVisible('.trade-row-mobile input[placeholder=\"단가 ($ USD)\"]').value)===100"),'US execution default must be native USD quote, not KRW');
 summary.push('New VT manual fill starts with native USD reference price');
 await value('.trade-row-mobile input[placeholder="수량 (주)"]',5);await value('.trade-row-mobile input[placeholder="단가 ($ USD)"]',100);
 const beforeBuy=await stat();oldBackend=true;
 await click('체결 내역 저장');
 await wait("document.body.innerText.includes('같은 요청의 결과 다시 확인')",'old backend pending');
 check((await stat()).trades===beforeBuy.trades,'Old backend received financial trade');
 check(await evaljs("Object.keys(localStorage).filter(k=>k.startsWith('portfolio_input_execution/') && k.endsWith('portfolio_trade_draft_v1_default')).some(k=>JSON.parse(localStorage.getItem(k)).pendingSubmission?.trades[0].execution.revision===1)"),'Frozen request lost connection metadata');
 await rpc('Page.reload');await wait("Boolean(window.qaVisible('[aria-label=\"포트폴리오 화면 선택\"]'))",'pending reload');oldBackend=false;await tab('tab8');await click('새 체결 내역 입력');loseTradeResponse=true;
 await click('같은 요청의 결과 다시 확인');await wait("[...document.querySelectorAll('button')].some(e=>e.textContent.trim()==='같은 요청의 결과 다시 확인' && !e.disabled)",'lost response pending');
 check((await stat()).trades===beforeBuy.trades+1,'Server did not commit before losing response');
 await rpc('Page.reload');await wait("Boolean(window.qaVisible('[aria-label=\"포트폴리오 화면 선택\"]'))",'lost response reload');await tab('tab8');
 await wait("Boolean(window.qaVisible('.execution-pending button'))",'completed task pending recovery');
 await evaljs("window.qaVisible('.execution-pending button').click()");
 await click('같은 요청의 결과 다시 확인');await wait("!document.body.innerText.includes('같은 요청의 결과 다시 확인')",'VT recorded');await tab('tab8');await wait("Boolean(window.qaVisible('.execution-current'))",'progress after retry');
 const after=await stat();check(after.trades===beforeBuy.trades+1,'Retry after lost response duplicated trade');
 check(after.cash.find(a=>a.id==='qa_acc').deposit_usd===0,'VT cash not spent');
 check(after.holdings.find(h=>h.asset_id==='qa_vt').quantity===10,'VT recording count wrong');
 check(Math.abs(after.holdings.find(h=>h.asset_id==='qa_vt').buy_fx_rate-1315)<0.00001,'Weighted FX basis not preserved');
 check(await current()==='계획한 작업이 모두 기록되었습니다','Workflow not completed');
 summary.push('FX uses existing USD; manual VT blocked on old backend; reload and lost-response retry record once and preserve FX basis');
 for(const width of [320,390,430,1280]){
  await rpc('Emulation.setDeviceMetricsOverride',{width,height:1000,deviceScaleFactor:1,mobile:width<600});await evaljs('scrollTo(0,0)');await delay(150);
  check(await evaljs('document.documentElement.scrollWidth<=innerWidth'),'Overflow at '+width);
  await screenshot('complete-'+width);
 }
 await click('이번 투자 종료');await wait("document.body.innerText.includes('이번 투자를 종료했습니다')",'report');
 check(JSON.stringify((await stat()).cash)===JSON.stringify(after.cash),'Closing changed cash');
 await screenshot('closed-1280');summary.push('320/390/430/1280 layouts fit; close keeps journal and report');
 const qaApi=(p,body,method=body?'POST':'GET')=>evaljs("(async()=>{const session=JSON.parse(sessionStorage.getItem('portfolio_api_session_v1'));const r=await fetch('http://127.0.0.1:5197'+"+JSON.stringify(p)+",{method:"+JSON.stringify(method)+",headers:{Authorization:'Bearer '+session.access_token,'Content-Type':'application/json'},body:"+JSON.stringify(body?JSON.stringify(body):undefined)+"});const data=await r.json();if(!r.ok)throw new Error(JSON.stringify(data));return data;})()");
 const returnSource=(await qaApi('/api/investments/default')).history[0].id;
 const returnFunding=await qaApi('/api/nh-notices/default/context?day='+qaDay);
 const returnExpected=Object.fromEntries(returnFunding.accounts.filter(a=>['qa_cma','qa_acc'].includes(a.id)).map(a=>[a.id,{deposit_krw:a.deposit_krw,deposit_usd:a.deposit_usd}]));
 await qaApi('/api/nh-notices/default/batch',{request_id:crypto.randomUUID(),confirmed:true,expected_cash:returnExpected,rows:[{kind:'WITHDRAW',account_id:'qa_cma',destination_account_id:'qa_acc',external:false,event_date:qaDay,krw_amount:20000,notes:'Synthetic leftover cash for recovery'}]});
 await click('남은 현금 CMA 회수 계획 만들기');
 await wait("Boolean(window.qaVisible('[aria-label=\"회수 CMA 계좌\"]'))",'cash recovery options');
 check(await evaljs("document.body.innerText.includes('절세계좌 · 출금 제외')"),'Protected account not explained');
 await value('[aria-label="검증 VT 계좌 남길 원화"]',2000);
 const returnBefore=await stat();
 await click('회수 금액 미리 확인');await wait("document.body.innerText.includes('총 회수액')",'recovery preview');
 await click('확인한 회수 계획 저장');await wait("document.body.innerText.includes('현금 회수 계획을 저장했습니다')",'recovery plan saved');
 check(JSON.stringify(await stat())===JSON.stringify(returnBefore),'Recovery plan save changed journal');
 await screenshot('cash-return-plan-1280');
 await click('이 회수 계획으로 진행');await wait("Boolean(window.qaVisible('.execution-start'))",'return plan start');
 await click('필요한 작업 미리 확인');await wait("Boolean(window.qaVisible('.execution-start-review'))",'return workflow preview');
 await tick('자금 사용 범위와 목표');await click('확인한 계획으로 투자 시작');
 await wait("window.qaVisible('.execution-current h3')?.textContent.includes('CMA로')",'return task');
 await click('새 실행 내역 입력');await click('직접 입력');await value('[aria-label="이체 금액"]',18000);await tick('실제 이체한 계좌');await click('확인한 이체 장부에 반영');
 await wait("!window.qaVisible('#execution-input-panel')",'recovery transfer recorded');
 const returned=await stat();check(returned.cash.find(a=>a.id==='qa_acc').deposit_krw===2000,'Recovery retained cash mismatch');
 check(returned.cash.find(a=>a.id==='qa_cma').deposit_krw===returnBefore.cash.find(a=>a.id==='qa_cma').deposit_krw+18000,'Recovery CMA mismatch');
 check(returned.trades===returnBefore.trades,'Recovery created a trade');
 await click('이번 투자 종료');await wait("document.body.innerText.includes('이번 투자를 종료했습니다')",'recovery ended');
 summary.push('Closed investment recovery excludes protected accounts, adjusts retained KRW, saves a separate plan without cash changes, records one common-ledger transfer and closes');

 await evaljs("[...document.querySelectorAll('details')].find(e=>e.querySelector('summary')?.textContent==='지난 투자 보기').open=true");
 await value('[aria-label="지난 투자 선택"]',(await qaApi('/api/investments/default')).history[0].id);
 await wait("document.body.innerText.includes('이번 투자를 종료했습니다')",'closed report');
 await evaljs("window.qaVisible('.execution-heading').scrollIntoView({block:'start'})");await screenshot('report-390');
 await value('[aria-label="지난 투자 선택"]','');
 await wait("Boolean(window.qaVisible('.execution-start'))",'new start again');
 const plan=await qaApi('/api/plans/default',{name:'기록 연결 · 합성 검증',scenario:'NEW_CASH',new_cash_krw:0,drift_threshold:5,trade_plan:[{account_id:'qa_isa',account_alias:'검증 ISA',asset_id:'qa_nh_bond',asset_name:'ACE 미국10년국채액티브',type:'BUY',qty:2,price:9000,total_krw:18000}],transfer_plan:[]});
 await evaljs("window.qaVisible('header button[title=\"새로고침\"]')?.click()");await tab('tab1');await tab('tab8');
 await wait("window.qaVisible('[aria-label=\"투자 실행 계획\"]').innerText.includes('기록 연결')",'new plan');
 await value('[aria-label="투자 실행 계획"]',plan.id);await value('[aria-label="투자 대표 계좌"]','qa_cma');
 await noBuffers();await click('필요한 작업 미리 확인');await wait("Boolean(window.qaVisible('.execution-start-review'))",'preview');
 await tick('자금 사용 범위와 목표');await click('확인한 계획으로 투자 시작');await wait("Boolean(window.qaVisible('.execution-current'))",'cycle');
 const initial=await stat();
 await click('잠시 중단');await wait("document.body.innerText.includes('잠시 멈춘 투자')",'paused');
 check(JSON.stringify(await stat())===JSON.stringify(initial),'Pause changed ledger');
 await click('투자 이어가기');await wait("!document.body.innerText.includes('잠시 멈춘 투자')",'resumed');
 await evaljs("[...document.querySelectorAll('details')].find(e=>e.querySelector('summary')?.textContent==='남은 매수 목표 변경').open=true");
 await value('input[aria-label$="매수 목표"]',1);await value('[aria-label="투자 목표 변경 이유"]','합성 검증 · 매수 규모 축소');
 await click('변경한 목표 반영');await wait("document.body.innerText.includes('9,000')",'goal updated');
 check(JSON.stringify(await stat())===JSON.stringify(initial),'Goals changed ledger');
 const ctx=await qaApi('/api/nh-notices/default/context?day='+qaDay);
 const expected=Object.fromEntries(ctx.accounts.filter(a=>['qa_cma','qa_isa'].includes(a.id)).map(a=>[a.id,{deposit_krw:a.deposit_krw,deposit_usd:a.deposit_usd}]));
 await qaApi('/api/nh-notices/default/batch',{request_id:crypto.randomUUID(),confirmed:true,expected_cash:expected,rows:[{kind:'WITHDRAW',account_id:'qa_cma',destination_account_id:'qa_isa',external:false,event_date:qaDay,krw_amount:9000,notes:'합성 기존 이체'}]});

 await click('기록한 거래 가져오기');await wait("Boolean(window.qaVisible('.execution-candidate input'))",'transfer candidate');
 const beforeLink=await stat();
 await evaljs("window.qaVisible('.execution-candidate input').click()");
 await click('이번 투자 회차에 연결');await wait("window.qaVisible('.execution-current h3')?.textContent.includes('매수')",'transfer linked');
 check(JSON.stringify(await stat())===JSON.stringify(beforeLink),'Existing transfer duplicated cash');
 await qaApi('/api/trades/batch',{request_id:crypto.randomUUID(),portfolio_id:'default',trade_date:qaDay,trades:[{account_id:'qa_isa',asset_id:'qa_nh_bond',trade_type:'BUY',quantity:1,price:9000,currency:'KRW'}]});
 await click('기록한 거래 가져오기');await wait("Boolean(window.qaVisible('.execution-candidate input'))",'trade candidate');
 const beforeTradeLink=await stat();
 await evaljs("window.qaVisible('.execution-candidate input').click()");
 await click('이번 투자 회차에 연결');await wait("window.qaVisible('.execution-current h3')?.textContent==='계획한 작업이 모두 기록되었습니다'",'trade linked');
 check(JSON.stringify(await stat())===JSON.stringify(beforeTradeLink),'Existing trade duplicated holdings');
 await evaljs("window.qaVisible('.execution-heading').scrollIntoView({block:'start'})");await screenshot('linked-390');
 const recorded=(await qaApi('/api/trades/?portfolio_id=default')).trades.find(t=>t.asset_id==='qa_nh_bond' && t.quantity===1);
 check(recorded,'Synthetic trade not found');
 await qaApi('/api/trades/batch',{trade_ids:[recorded.id]},'DELETE');
 await evaljs("[...document.querySelectorAll('details')].find(e=>e.querySelector('summary')?.textContent==='지난 투자 보기').open=true");
 await click('투자 기록 새로고침');await wait("window.qaVisible('.execution-current h3')?.textContent.includes('매수')",'cancel reflected');
 check((await stat()).holdings.find(h=>h.asset_id==='qa_nh_bond').quantity===20,'Cancel holding wrong');
 await evaljs("[...document.querySelectorAll('details')].find(e=>e.querySelector('summary')?.textContent==='미실행 작업을 남기고 종료').open=true");
 await value('[aria-label="투자 종료 이유"]','합성 검증 · 취소 후 미실행 종료');await click('이유를 남기고 투자 종료');
 await wait("document.body.innerText.includes('이번 투자를 종료했습니다')",'partial report');
 summary.push('Past report, pause/resume, target revision, existing transfer and trade links preserve journal, real cancellation reopens task, partial closure');

 await rpc('Emulation.setDeviceMetricsOverride',{width:390,height:1000,deviceScaleFactor:1,mobile:true});
 delayPortfolio='cash_only';await value('header select','cash_only');for(let i=0;i<40 && !heldBundle;i++)await delay(100);check(heldBundle,'Delayed bundle not intercepted');
 check(await evaljs("!window.qaVisible('.execution-start') && !window.qaVisible('.execution-current')"),'Old portfolio form visible before new account data');
 const paused=heldBundle;delayPortfolio='';heldBundle=null;await rpc('Fetch.continueRequest',{requestId:paused});await wait("window.qaVisible('[aria-label=\"투자 대표 계좌\"]')?.value==='qa_cash'",'fresh portfolio account');
 summary.push('Portfolio switch waits for its own account bundle and never proposes the previous accounts');

 oldBackend=true;await tab('tab1');await tab('tab8');
 await wait("document.body.innerText.includes('지원 여부 다시 확인')",'old server disabled workspace');
 const investmentReads=requests.filter(r=>r.path.startsWith('/api/investments')).length;
 await tab('tab4');await click('직접 입력');await click('외부 입출금');
 await wait("Boolean(window.qaVisible('[aria-label=\"입출금 계좌\"]'))",'ordinary cash form');
 await value('[aria-label="입출금 계좌"]','qa_cash');await value('[aria-label="입출금 금액"]',100);
 await tick('외부 입출금이며');await click('외부 입출금 기록 저장');
 await wait("window.qaVisible('[aria-label=\"입출금 금액\"]')?.value===''",'ordinary cash saved');
 await delay(400);
 check((await qaApi('/api/nh-notices/cash_only/context?day='+qaDay)).accounts[0].deposit_krw===100,'Legacy independent cash not recorded');
 check(!await evaljs("document.body.innerText.includes('투자 진행') && document.body.innerText.includes('화면 갱신 실패')"),'Unavailable investment broke independent cash refresh');
 check(requests.filter(r=>r.path.startsWith('/api/investments')).length===investmentReads,'Independent write queried unavailable investment');
 oldBackend=false;summary.push('Old server disables only execution; ordinary tab 5 deposit saves and refreshes without an execution request');

 await writeFile(path.join(root,'results.json'),JSON.stringify({summary,financialPosts:requests.filter(r=>r.method==='POST' && ['/api/trades/batch','/api/nh-notices/default/batch'].includes(r.path)).length},null,2));
 console.log(JSON.stringify(summary,null,2));
}catch(e){console.error(e.message);console.error(JSON.stringify(summary));process.exitCode=1;}finally{ws?.close();if(chrome.pid)await new Promise(resolve=>{const stopped=spawn('taskkill',['/PID',String(chrome.pid),'/T','/F'],{windowsHide:true,stdio:'ignore'});stopped.on('exit',resolve);stopped.on('error',resolve);});}
