# .streamlit/secrets.toml

# Supabase PostgreSQL Connection String
SUPABASE_URL = "postgresql://postgres.skeihahzseeyglvlprbe:Qgieksn631%23sdg@aws-1-ap-northeast-2.pooler.supabase.com:6543/postgres"

# App Login Password
APP_PASSWORD = "bluekind00!"
